version: "3.7"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  quasar:
    build:
    context: .
    target: "develop-stage"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: /bin/sh -c "npm && quasar dev"

volumes:
  postgres_data:
