# Generated by Django 3.2.3 on 2021-05-23 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringvalue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stringvalue',
            name='name',
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=models.TimeField()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='variable_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.variable'),
            preserve_default=False,
        ),
    ]
