# Generated by Django 3.2.3 on 2021-05-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210523_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringvalue',
            name='date',
        ),
    ]
