# Generated by Django 3.2.3 on 2021-05-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_stringvalue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringvalue',
            name='Value',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stringvalue',
            name='variable_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='task.variable'),
        ),
    ]
